steps:
# Debug step to verify working directory
- name: 'alpine'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      echo "Current working directory:"
      pwd
      echo "Directory contents:"
      ls -la
      echo "Parent directory contents:"
      ls -la ..

- name: "alpine"
  entrypoint: "sh"
  args: ["-c", "chmod -R 755 /workspace"]

- name: "python"
  entrypoint: "pip"
  args: ["install", "-r", "../requirements.txt"]

- name: "docker"
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker build \
        -t gcr.io/$PROJECT_ID/gcpdevops \
        -f ../Dockerfile \
        .. || {
          echo "Docker build failed"
          exit 1
        }

images: 
  - 'gcr.io/$PROJECT_ID/gcpdevops'
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "N1_HIGHCPU_8"
timeout: "1200s"