steps:
# Debug step - can be removed once pipeline is working
- name: 'alpine'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      echo "Current working directory:"
      pwd
      echo "Directory contents:"
      ls -la
      echo "Parent directory contents:"
      ls -la ..

- name: "docker"
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/gcpdevops',
    '-f', '/workspace/Dockerfile',
    '/workspace'
  ]

# Get GKE credentials 
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'container'
  - 'clusters'
  - 'get-credentials'
  - 'devops-gke'
  - '--zone=us-central1-a'
  - '--project=$PROJECT_ID'

# Create namespace
- name: "gcr.io/cloud-builders/kubectl"
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=devops-gke'
  args: 
  - 'apply'
  - '-f'
  - 'k8s/namespace.yaml'
  
# Deploy to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args: 
  - 'run'
  - '--filename=k8s/'
  - '--location=us-central1-a'
  - '--cluster=devops-gke'
  - '--namespace=gcp-devops-project'
  - '--image=gcr.io/$PROJECT_ID/gcpdevops:latest'

images: 
  - 'gcr.io/$PROJECT_ID/gcpdevops'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "N1_HIGHCPU_8"
timeout: "1200s"