steps:
- name: "python"
  entrypoint: "pip"
  args: ["install", "-r", "requirements.txt"]
# - name: "python"
#   entrypoint: "python"
#   args: ["-m", "unittest", "discover"]
- name: "docker"
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcpdevops', '-f', 'Dockerfile', '..']
images: 
  - 'gcr.io/$PROJECT_ID/gcpdevops'
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "N1_HIGHCPU_8"  # Specify a machine type with more resources
timeout: "1200s"  # Set timeout to 20 minutes



