steps:
- name: 'alpine'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      echo "Current working directory:"
      pwd
      echo "Directory contents:"
      ls -la
      echo "Parent directory contents:"
      ls -la ..

- name: "docker"
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/gcpdevops',
    '-f', '/workspace/Dockerfile',
    '/workspace'
  ]
images: 
- 'gcr.io/$PROJECT_ID/gcpdevops'

## Deploy the container to GKE

- name: "gcr.io/cloud-builders/gke-deploy"
  args: 
  -  'run'
  - --filename=k8s/manifest.yaml
  - --location=us-central1-a
  - --cluster=devops-gke
  - --namespace=gcp-devops-project
  - --image=gcr.io/$PROJECT_ID/gcpdevops:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "N1_HIGHCPU_8"
timeout: "1200s"  